appuio/component-openshift4-nodes

CHANGELOG.md
Makefile
class/defaults.yml
component/main.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
docs/modules/ROOT/partials/nav.adoc

Initial implementation.
* Adds ability for managing MachineSets in a simple streamline fashion by providing some syntactic sugar.
* Also allows to control each aspect of the resulting MachineSet.
* Does not take care of auto scaling. See #5.

Add basic ability to configure MachineSets

---

class/defaults.yml
class/openshift4-nodes.yml
component/common.libsonnet
component/kubelet.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/defaults/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml

* Supports managing `KubeletConfig`s
* Configures a pod limit of 110 per node using `KubeletConfig`
NOTE: rolling this out may trigger kubelet restarts on all workers but not necessarily restart the workers.

Configure Pod Limit per node

---

component/machine-sets.jsonnet

See https://syn.tools/commodore/reference/deprecation-notices.html#_v0_3_0
Fixes #9

Use `parameters.facts.cloud` instead of deprecated `parameters.cloud.provider`

---

class/defaults.yml

We've deprecated `cloud.region` a while ago

Fix cloud region reclass reference

---

.github/workflows/test.yaml
.sync.yml
Makefile.vars.mk
component/machine-sets.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/gcp.yml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/debug.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-infra-a.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-infra-b.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-infra-c.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-worker.yaml

The GCP-specific fields are not supported by ProviderSpecs like
`awsproviderconfig.openshift.io/v1beta1` or `vsphereprovider.openshift.io/v1beta1`.
Rendering them into the ProviderSpec by default makes the MachineSet
part of this component incompatible with any other ProviderSpec than `gcpprovider.openshift.io/v1beta1`.
Fixes #15

Only render GCP-specific fields when cloud is GCP

---

component/machine-sets.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/gcp.yml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-worker.yaml

This allows the configuration of custom annotations on MachineSets which
are used by operators like the [OpenShift MachineSet EgressCIDR operator](https://github.com/appuio/openshift-machineset-egress-cidr-operator).

Add support for annotations on MachineSets

---

component/machine-configs.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/10_machineconfigs.yaml
tests/machineconfig.yml

We implement support for key `contents.inline` for entries in Ignition parameter `storage.files`. This key doesn't exist upstream. We base64-encode the contents of the key and emit the base64-encoded contents as
```
source: data:text/plain;encoding=utf-8;base64,<contents|base64>
```
in the resulting Ignition config.
See https://coreos.github.io/ignition/configuration-v3_2/ for the Ignition spec.
changelog.

Add support for inline file contents in machine configs

---

class/openshift4-nodes.yml
component/aggregated-clusterroles.jsonnet
tests/golden/defaults/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/maxpods/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/syn-monitoring/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml

The other custom resources (MachineConfigPools, ControllerConfigs, KubeletConfigs, and ContainerRuntimeConfigs) are covered by cluster role `system:openshift:machine-config-operator:cluster-reader`.
changelog.

Aggregate read-only permissions for MachineConfig resources to `cluster-reader`

---

component/aggregated-clusterroles.jsonnet
tests/golden/defaults/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/maxpods/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/syn-monitoring/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml

Correctly use `rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"` as a label instead of an annotation.
Fixes #59 
changelog.

Fix aggregating read permissions for machineconfig resources

---

.cruft.json
.github/workflows/test.yaml
Makefile.vars.mk
component/machine-config-pools.libsonnet
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/debug.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/machineconfigpool-app.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/machineconfigpool-infra.yaml
tests/remove-machineconfigpool.yml

Adjust the component to not choke on setting `machineConfigPools.<name> = null` in the hierarchy.
changelog.

Gracefully handle machineconfigpool removal

---

component/machine-configs.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/10_machineconfigs.yaml

The `data` URL scheme uses `charset` and not `encoding` to specify the encoding of the inline data.
This commit fixes the component to use `charset=utf-8` instead of `encoding=utf-8` when generating `data` URLs.
See also https://datatracker.ietf.org/doc/html/rfc2397
changelog.

Fix machineconfig inline file source encoding specification

---

component/kubelet.jsonnet
tests/golden/maxpods/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
tests/maxpods.yml

Until now, any other `kubeletConfig` contents were dropped when the component emitted the warning about `maxPods > 110`. This commit adjusts the warning implementation to not overwrite the `kubeletConfig` contents completely.
changelog.

Fix warning for `kubeletConfig.maxPods > 110`

---

class/defaults.yml
class/openshift4-nodes.yml
component/common.libsonnet
component/egress-interfaces.jsonnet
component/machine-configs.jsonnet
component/scripts/create-egress-interfaces.sh
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/30_egress_interfaces.yaml
tests/machineconfig.yml

See also https://github.com/projectsyn/component-cilium/pull/104 and https://github.com/projectsyn/component-cilium/pull/106
changelog.

Add support for deploying a systemd service which configures egress dummy interfaces

---

component/machine-sets.jsonnet
tests/gcp.yml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-master.yaml

If using a NodeGroup named `master` a ControlPlaneMachineSet will be created instead of a normal MachineSet.
changelog.

Support creating ControlPlaneMachineSet

---

docs/modules/ROOT/pages/references/parameters.adoc

Extend documentation with information on how to manage a `ControlPlaneMachineSet`

---

class/defaults.yml
component/machine-sets.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-master.yaml

Use seperate defaultSpecs for ControlPlaneMachineSet

---

.cruft.json
component/app.jsonnet
component/autoscaler.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/autoscaling/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/defaults/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/gcp/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/machineconfig/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/maxpods/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/pidslimit/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/apps/openshift4-nodes.yaml

We need to ignore changes to `spec.replica` when diffing *and* syncing MachineSets which are managed by a `MachineAutoscaler`.
To do so we 1) dynamically configure `spec.ignoreDifferences` in the ArgoCD app to ignore `spec.replicas` of each `MachineSet` that's targeted by a `MachineAutoscaler` and 2) set ArgoCD sync option `RespectIgnoreDifferences=true` to ensure that we don't overwrite the machine autoscaler's value in `spec.replicas` if we're applying other changes.
changelog.

Ignore `spec.replicas` for autoscaled MachineSets in ArgoCD sync

---

class/defaults.yml
class/openshift4-nodes.yml
component/prune-machine-configs.jsonnet
component/scripts/machineconfig_pruning.sh
tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/defaults/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/maxpods/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml

Adds a cronjob to regularly (once a week) prune unused rendered machineconfigs. Uses `oc adm prune renderedmachinconfigs` as described in https://docs.openshift.com/container-platform/4.16/machine_configuration/machine-configs-garbage-collection.html#machine-configs-garbage-collection
Instead of pruning all unused rendered machineconfigs we keep the 5 most recent rendered machineconfigs for each machineconfigpool. This is useful for debugging issues and tasks like https://kb.vshn.ch/oc4/how-tos/force-reboot.html
changelog.

Cronjob to prune unused rendered MachineConfigs

---

.cruft.json
.github/workflows/test.yaml
Makefile.vars.mk
class/defaults.yml
class/openshift4-nodes.yml
component/capacity.jsonnet
docs/modules/ROOT/pages/explanations/resource_management.adoc
docs/modules/ROOT/pages/references/parameters.adoc
docs/modules/ROOT/partials/nav.adoc
tests/autoscaling.yml
tests/capacity.yml
tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/capacity_alerting_rules.yaml
tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/machine_autoscalers.yaml
tests/golden/capacity/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/capacity_alerting_rules.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/debug.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/machineconfigpool-app.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/machineconfigpool-infra.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/machineconfigpool-storage.yaml

The alert rules are adapted from component-openshift4-monitoring. The documentation is also blatantly yoinked from there, with only minor changes to account for the changes to alert rule configuration and behaviour.
changelog.

Add capacity alerts with autoscaling support

---

component/autoscaler.jsonnet
tests/golden/autoscaling/openshift4-nodes/apps/openshift4-nodes.yaml

Use correct api group to ignore cluster autoscaler difference

---

component/scripts/machineconfig_pruning.sh
tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/capacity/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/defaults/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/maxpods/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml

`grep 'in use: false'` will be empty on a fresh cluster, forcing the script to error out early with pipefail
changelog.

Remove pipefail bash setting in mc pruning cronjob

---

class/defaults.yml
component/autoscaler.jsonnet
component/espejote-templates/patch-autoscaler-args.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/autoscaling-scheduled.yml
tests/autoscaling.yml
tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/autoscaler_inject_args_admission.yaml
tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/autoscaler_inject_args_jsonnetlibrary.yaml

Adds some sane defaults:
- `--daemonset-eviction-for-occupied-nodes`: Stops things like CSI drivers to be evicted.
- `--skip-nodes-with-local-storage`: Allows node deletion even if pods use `emptyDir`.
Uses the espejote dynamic admission feature to patch arguments.
changelog.

Patch autoscaler args

---

.cruft.json
.github/workflows/test.yaml
Makefile.vars.mk
class/defaults.yml
class/openshift4-nodes.yml
component/espejote-templates/nodedisruptionpolicies-template.jsonnet
component/espejote-templates/nodedisruptionpolicy-helpers.libsonnet
component/node-disruption-policies.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/node-disruption-policies/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/debug.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfigpool-app.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfigpool-infra.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfigpool-storage.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/nodedisruptionpolicies_managedresource.yaml
tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/nodedisruptionpolicies_rbac.yaml
tests/node-disruption-policies.yml

Node disruption policy entries can be provided via component parameter `nodeDisruptionPolicies` or by adding annotation
`openshift4-nodes.syn.tools/node-disruption-policies` with string-encoded JSON contents.
changelog.

Support confguring node disruption policies

---

.cruft.json
.github/workflows/test.yaml
Makefile.vars.mk
class/defaults.yml
component/machine-sets.jsonnet
tests/cloudscale.yml
tests/golden/cloudscale/openshift4-nodes/apps/openshift4-nodes.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/debug.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/machineconfigpool-app.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/machineconfigpool-infra.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/machineconfigpool-storage.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/machineset-infra.yaml
tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/machineset-worker.yaml

In addition, this PR enables overriding the machineset providerSpec in the hierarchy.
changelog.

Add support for anti-affinity keys on Cloudscale clusters
