- .github/workflows/test.yaml
- CHANGELOG.md
- class/defaults.yml
- component/main.jsonnet
> Fix node role label

- class/defaults.yml
To prevent breaking the reclass inventory.
> Set default values

- CHANGELOG.md
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
Also use the group name as default role name.
Fixes #4
> Always add worker role label

- CHANGELOG.md
- component/main.jsonnet
Since the tag is used in firewall rules.
> Always use the worker tag for nodes

- CHANGELOG.md
- component/main.jsonnet
> Separate Files for MachineSets

- CHANGELOG.md
- component/main.jsonnet
Add .gitkeep if no MachineSets are specified.
> Add .gitkeep if no MachineSets are specified

- .sync.yml
> Prepare for modulesync

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
Fixes a config error as follow-up of #19 
> Fix default matchExpression in kubelet

- docs/modules/ROOT/pages/references/parameters.adoc
> Improve documentation for parameter `defaultSpecs`

- tests/gcp.yml
- tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-infra-a.yaml
- tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-infra-b.yaml
- tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-infra-c.yaml
> Add test to override default ProviderSpec value

- .github/workflows/test.yaml
- .sync.yml
- Makefile.vars.mk
- class/defaults.yml
- class/openshift4-nodes.yml
- component/container-runtime.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
- tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/20_containerruntimeconfigs.yaml
- tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/debug.yaml
- tests/pidslimit.yml
> Add support for ContainerRuntimeConfigs

- docs/modules/ROOT/pages/explanations/machine-config-pool.adoc
- docs/modules/ROOT/partials/nav.adoc
This should properly explain the changes introduced in https://github.com/appuio/component-openshift4-nodes/pull/50
> Add explanation for Machine Config Pool Management

- CODEOWNERS
> Update CODEOWNERS to @appuio/aldebaran

- CODEOWNERS
- tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/10_machineconfigs.yaml
changelog.
- [-] Update the documentation.
- [-] Link this PR to related issues or PRs.
> Switch CodeOwners to Aldebaran Tech

- class/defaults.yml
- class/openshift4-nodes.yml
- component/node-config.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/gcp/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/maxpods/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/syn-monitoring/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
> Support configuring cgroupMode

- component/egress-interfaces.jsonnet
- tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/30_egress_interfaces.yaml
Adjust egress-interfaces MachineConfig to have correct format.
Follow-up for #76 
changelog.
> Fix egress-interfaces MachineConfig

- .cruft.json
- class/defaults.yml
- class/openshift4-nodes.yml
- component/app.jsonnet
Template version: main (`f12cbb4`)
changelog.
> Update from template

- class/defaults.yml
- component/autoscaler.jsonnet
- component/autoscaling-metrics.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/autoscaling.yml
- tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/autoscaling_metrics_prometheusrules.yaml
> Export autoscaling parameters as metrics

- class/defaults.yml
- component/autoscaler.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/autoscaling-scheduled.yml
- tests/golden/autoscaling-scheduled/openshift4-nodes/apps/openshift4-nodes.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/additional_machine_sets.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/autoscaling_metrics_prometheusrules.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/capacity_alerting_rules.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/cluster_autoscaler.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/debug.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/downscale_cronjobs.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/machine_autoscalers.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/machineconfigpool-app.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/machineconfigpool-infra.yaml
- tests/golden/autoscaling-scheduled/openshift4-nodes/openshift4-nodes/machineconfigpool-storage.yaml
> Add option to enable / disable downscaling in a set time window

- component/aggregated-clusterroles.jsonnet
- tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/capacity/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/cloudscale/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/defaults/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/gcp/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/maxpods/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/openstack/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
- tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
> Aggregate read permissions for ControlPlaneMachineSet to cluster-reader
